version: '2'

networks:
  proxy-tier:
    external:
      name: nginx-proxy
  data-tier:
    driver: bridge

services:
  storage:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: jilu
      MYSQL_ROOT_PASSWORD: mysqlpassword
    networks:
      - data-tier

  laravel:
    image: webdevops/php-nginx:alpine-3
    restart: always
    depends_on:
      - storage
    volumes:
      - ./Api:/application/code
      - ./Entrypoint/Api:/opt/docker/provision/entrypoint.d
    environment:
      - WEB_DOCUMENT_ROOT=/application/code/public
      - WEB_ALIAS_DOMAIN=jilucdn.shmeta.com
      - VIRTUAL_HOST=jilucdn.shmeta.com
#        - LETSENCRYPT_HOST=jilucdn.shmeta.com
#        - LETSENCRYPT_EMAIL=luba@shmeta.com
    ports:
      - "8188:80"
    networks:
      - proxy-tier
      - data-tier

#  client:
#    image: node:6
#    restart: always
#    volumes:
#      - ./Client:/usr/src/app
#      - ./Entrypoint/Client:/usr/src/Entrypoint
#    command: bash /usr/src/Entrypoint/production.sh
#    environment:
#      - VIRTUAL_HOST=jilucdn.shmeta.com
##        - LETSENCRYPT_HOST=jilu.shmeta.com
##        - LETSENCRYPT_EMAIL=luba@shmeta.com
#    ports:
#      - "8187:8080"
#    networks:
#      - proxy-tier
